<?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Читателям");
?><p>
</p>
<div>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">1.&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"><a href="/libraries/apush/chitatelyam/konkursy-proekty/ПРАВИЛА%20пользования%20библиотекой.pdf" target="_blank">Правила пользования библиотекой</a></span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">2.&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"><a href="http://www.biblio.e-nkama.ru/chitatelyam/%D0%9F%D0%A0%D0%90%D0%92%D0%98%D0%9B%D0%90%20%D0%9F%D0%9E%D0%9B%D0%AC%D0%97%D0%9E%D0%92%D0%90%D0%9D%D0%98%D0%AF%20%D0%98%D0%9D%D0%A2%D0%95%D0%A0%D0%9D%D0%95%D0%A2%D0%9E%D0%9C.pdf" target="_blank">Правила пользования сетью Интернет</a></span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">3.&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"><a href="http://biblio.e-nkama.ru/onlayn-prodlenie/" target="_blank">Онлайн продление книг</a></span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">4.&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"><a href="/chitatelyam/kluby-po-interesam/index.php">Клубы по интересам</a></span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">5.&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"><a href="/chitatelyam/konkursy/index.php">Конкурсы</a></span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">6.&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"><a href="/chitatelyam/sovetuem-pochitat/index.php">Советуем почитать</a> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">7.&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"><a href="/chitatelyam/onlayn-opros/index.php">Онлайн-опрос</a>&nbsp;<br>
 </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">8.&nbsp;</span> &nbsp; &nbsp;<span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"><a href="/chitatelyam/biblioteki-v-sotsialnykh-setyakh/index.php">Библиотеки в социальных сетях</a><br>
 </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;">9.&nbsp; &nbsp; &nbsp;<a href="http://biblio.e-nkama.ru/chitatelyam/vov/index.php">Наш&nbsp;край в годы войны</a><br>
 </span>
</div>
<p>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span>
</p>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 14pt;"> </span><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>